[feat][TRIP-10326] Add sentry captureMessage to Google calendar services
tourlane/cal.com pull request #72
Opened 2023-10-23 14:58 UTC by RubLo

## Context/Change

https://tourlane.atlassian.net/browse/TRIP-10326

2023-10-23 15:16 UTC, haffla requested changes
Since you have the `error` object at hand maybe just use `Sentry.captureException(error)`?

2023-10-23 15:21 UTC, RubLo commented
@haffla I thought about that, but in this way adding an extra bit of string we have a nicer visualization in the sentry report when example hits the slack channel.

The error then is also available in the sentry app

2023-10-23 15:44 UTC, haffla commented
The visualization was actually my concern. This will result in quite long strings and I am not sure what "....: ${error}" will return. I think Sentry displays errors in a good way.

2023-10-24 08:11 UTC, haffla requested changes

2023-10-24 08:11 UTC, haffla commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +            Sentry.captureException(err);
I think here we actually don't want to always report the error. Only if the error code is not equal to 404 and not equal to 410. Only when this code returns a rejected promise, should we report the error.

2023-10-24 08:32 UTC, merged